// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/easydose-home/V1CenteredStack.tsx": () => import("../components/mockups/easydose-home/V1CenteredStack.tsx"),
  "./components/mockups/easydose-home/V2SplitImmersive.tsx": () => import("../components/mockups/easydose-home/V2SplitImmersive.tsx"),
  "./components/mockups/easydose-home/V3Editorial.tsx": () => import("../components/mockups/easydose-home/V3Editorial.tsx")
};
